# Generated by Django 4.2.3 on 2023-07-16 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.IntegerField()),
                ('mobile_code', models.TextField(max_length=32)),
                ('tag', models.TextField()),
                ('timezone', models.CharField(default='GMT+3', max_length=32)),
            ],
            options={
                'db_table': 'Client',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Malling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_time_start', models.DateTimeField()),
                ('message_text', models.TextField()),
                ('mobile_code', models.TextField(blank=True, max_length=32)),
                ('tag', models.TextField(blank=True)),
                ('day_time_end', models.DateTimeField()),
            ],
            options={
                'db_table': 'Malling',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_time_create', models.DateTimeField(auto_now_add=True)),
                ('status', models.TextField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.client')),
                ('malling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.malling')),
            ],
            options={
                'db_table': 'Message',
                'managed': True,
            },
        ),
    ]
